### ISSUE TITLE
Fix readme.md

### ISSUE THREAD

**Issue by ikarofelix** [projeto-dev404/alpha-squad#5]
Nao tinha tido tempo para conferir o readme, so tinha visto o upload, fui conferir agora e vi certos erros da api.
Fiz no notepad mesmo, acho que da pra entender

- Certifique-se de definir as variaveis de ambiente adequadas no arquivo .env de acordo com o .env.example antes de executar o contêiner.
Correcao: .env-example

- Criar um usuário
Método: POST
Endpoint: /auth/users
Corpo da solicitação (JSON):
{
    "name": "Novo Usuário",
    "email": "usuario@example.com",
    "password": "1234567890"
}
Correcao: recebe tambem a resposta com o usuario criado

- Obter os dados do usuário logado atualmente
Método: GET
Endpoint: /auth/users/me
Resposta (JSON):
{
   "name": "Nome",
   "id": "sa4f89-4894-asf8-6548-54fsa894f87d",
   "email": "usuario@example.com"
}
Correcao: Precisa passar o auth_token, o auth_token e adquirido atravas do #realizar_o_login
Header:

	Authorization: token auth_token_example(2b534e7c60930a7143a9fd05e308162a0e122b35)

- Obter dados do usuário especificado
Método: GET
Endpoint: /auth/users/:id
Resposta (JSON):
{
   "name": "Nome",
   "id": "sa4f89-4894-asf8-6548-54fsa894f87d",
   "email": "usuario@example.com"
}
Correcao: mesma coisa, precisa passar o auth token do user logado
Header:

	Authorization: token auth_token_example(2b534e7c60930a7143a9fd05e308162a0e122b35)

- Realizar logout
Método: POST
Endpoint: /auth/token/logout
Resposta (JSON):
{
  "HTTP_204_NO_CONTENT"
}
Correcao: mesma coisa, precisa passar o auth token do user logado

**Comment by skapskap** [comment]
Issue resolvido no pull request #6

**Comment by gcaldasl** [comment]
Issue resolvido no pull request https://github.com/projeto-dev404/alpha-squad/pull/6
